# action.yml
name: 'GitHub Action for LaTeX customized for 3tty0n'
description: 'GitHub Action to compile LaTeX documents'
author: Yusuke Izawa
inputs:
  root_file:
    description: The root LaTeX file to be compiled
    required: true
  args:
    description: Arguments passed to latexmk
    required: false
  working_dir:
    description: The place of your LaTeX file
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.root_file }}
    - ${{ inputs.args }}
    - ${{ inputs.working_dir }}
branding:
  icon: book
  color: black
