name: Testing My GitHub Actions
on: [push, pull_request]
jobs:
  compile_latex:
    runs-on: ubuntu-latest
    name: A job to compile a LaTeX document
    steps:
      - name: A job to compile a simple LaTeX document
        id: simple1
        uses: actions/latexmk-action@v1
        with:
          root_file: main.tex
