name: Testing Github Action
on: [push, pull_request]
jobs:
  compile_latex:
    runs-on: ubuntu-latest
    name: A job to compile a LaTeX document
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Simple compiling test
        uses: 3tty0n/latexmk-action@master
        with:
          root_file: main.tex
          args: -pdfxe
          working_dir: test
      - name: Compiling a TeX file written in Japanese with LuaLaTex
        uses: 3tty0n/latexmk-action@master
        with:
          root_file: main-ja.tex
          args: -pdflua
          working_dir: test
          extra_packages: fonts-noto-cjk
      - uses: actions/upload-artifact@v1
        with:
          name: main.pdf
          path: test/main.pdf
